import { Author, Category, NewsArticle, Post, Tag } from "@/types";

export const MOCK_AUTHORS: Author[] = [
  {
    _id: "author-aarav",
    name: "Dr. Aarav Mehta",
    slug: "aarav-mehta",
    role: "Chief Technology Editor & AI Architect",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    avatarAlt: "Portrait of Dr. Aarav Mehta",
    bio: "Dr. Aarav Mehta leads technical research at BlueCrest. Former Principal Engineer at AWS and PhD holder in Distributed Systems from IIT Bombay, Aarav writes about artificial intelligence, system scalability, and developer infrastructure.",
    expertise: ["Artificial Intelligence", "Cloud Architecture", "Next.js & Frontend", "Distributed Systems"],
    credentials: "PhD Distributed Systems (IIT Bombay), Ex-AWS Principal Engineer, 14+ years experience",
    socials: {
      twitter: "https://twitter.com/aaravmehta_tech",
      linkedin: "https://linkedin.com/in/aaravmehta",
      github: "https://github.com/aaravmehta",
      website: "https://bluecreast.in/author/aarav-mehta",
    },
  },
  {
    _id: "author-priya",
    name: "Priya Sengupta",
    slug: "priya-sengupta",
    role: "Senior Financial Markets Analyst",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    avatarAlt: "Portrait of Priya Sengupta",
    bio: "Priya Sengupta is a CFA Charterholder and veteran financial journalist with over a decade covering Indian equity markets, personal taxation, fintech regulation, and wealth building strategies.",
    expertise: ["Equity Markets", "Personal Taxation", "Mutual Funds", "Fintech & Banking"],
    credentials: "CFA Charterholder, M.Sc Finance (LSE), Former Senior Editor at Financial Express",
    socials: {
      twitter: "https://twitter.com/priyasengupta_fin",
      linkedin: "https://linkedin.com/in/priyasengupta",
    },
  },
  {
    _id: "author-ananya",
    name: "Dr. Ananya Sharma",
    slug: "ananya-sharma",
    role: "Medical Reviewer & Preventive Health Specialist",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
    avatarAlt: "Portrait of Dr. Ananya Sharma",
    bio: "Dr. Ananya Sharma is a practicing physician and preventive cardiology researcher. She consults for wellness ventures and translates complex clinical literature into actionable, evidence-based lifestyle protocols.",
    expertise: ["Preventive Medicine", "Circadian Biology", "Cardiometabolic Health", "Longevity"],
    credentials: "MD General Medicine (AIIMS New Delhi), Fellow American College of Physicians",
    socials: {
      twitter: "https://twitter.com/dr_ananyasharma",
      linkedin: "https://linkedin.com/in/drananyasharma",
    },
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    _id: "cat-tech",
    title: "Technology",
    slug: "technology",
    description: "Deep-dives into artificial intelligence, cloud architectures, cybersecurity, hardware reviews, and web engineering.",
    color: "#0B3D91",
  },
  {
    _id: "cat-fin",
    title: "Finance & Wealth",
    slug: "finance",
    description: "Actionable personal finance, Indian equity markets, mutual fund strategies, tax optimisation, and crypto fundamentals.",
    color: "#0F766E",
  },
  {
    _id: "cat-health",
    title: "Health & Longevity",
    slug: "health",
    description: "Evidence-based health insights, metabolic conditioning, nutritional protocols, and mental performance research.",
    color: "#15803D",
  },
  {
    _id: "cat-lifestyle",
    title: "Lifestyle & Travel",
    slug: "lifestyle",
    description: "Modern travel blueprints, mindful minimalism, remote work setups, cultural explorations, and urban living.",
    color: "#7E22CE",
  },
  {
    _id: "cat-biz",
    title: "Business & Leadership",
    slug: "business",
    description: "Venture building, product leadership, startup fundraising in India, career transitions, and management mental models.",
    color: "#C2410C",
  },
];

export const MOCK_TAGS: Tag[] = [
  { _id: "tag-ai", title: "Artificial Intelligence", slug: "ai" },
  { _id: "tag-nextjs", title: "Next.js", slug: "nextjs" },
  { _id: "tag-investing", title: "Investing", slug: "investing" },
  { _id: "tag-tax", title: "Taxation", slug: "taxation" },
  { _id: "tag-sleep", title: "Sleep Science", slug: "sleep-science" },
  { _id: "tag-cardio", title: "Cardiovascular Health", slug: "cardio" },
  { _id: "tag-remote", title: "Remote Work", slug: "remote-work" },
  { _id: "tag-india", title: "India Growth", slug: "india-growth" },
  { _id: "tag-hardware", title: "Hardware Review", slug: "hardware-review" },
  { _id: "tag-career", title: "Engineering Leadership", slug: "engineering-leadership" },
];

export const MOCK_POSTS: Post[] = [
  {
    _id: "post-1",
    title: "The 2026 State of Generative AI in Production: Architecture, Inference Costs, and Real-World Latency",
    slug: "generative-ai-production-architecture-costs-2026",
    excerpt: "An architectural review of deploying small open-weights models versus cloud LLMs. We analyze KV-cache compression, speculative decoding, and how top engineering teams trim inference bills by 65%.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=85",
      alt: "Abstract neural network glowing circuits representing generative AI inference in data centers",
      caption: "Neural inference clusters operating on modern high-bandwidth memory architectures.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[0],
    tags: [MOCK_TAGS[0], MOCK_TAGS[1]],
    author: MOCK_AUTHORS[0],
    publishedAt: "2026-10-06T10:30:00.000Z",
    updatedAt: "2026-10-07T14:15:00.000Z",
    readingTime: 8,
    seoTitle: "Generative AI in Production: Architecture, Costs & Real-World Latency (2026)",
    seoDescription: "Comprehensive benchmark and guide for deploying production LLMs in 2026. Explore speculative decoding, KV-cache quantization, and practical server architectures.",
    featured: true,
    trending: true,
    views: 14250,
    body: [
      {
        _key: "b1",
        _type: "block",
        style: "normal",
        children: [{ _key: "c1", _type: "span", text: "Deploying generative artificial intelligence models to production in 2026 is no longer about slapping a wrapper around a monolithic proprietary API. As traffic compounds and unit economics face rigorous audit committees, engineering organizations have pivoted toward hybrid routing, local distillation, and hardware-aware inference optimization." }],
      },
      {
        _key: "b2",
        _type: "block",
        style: "h2",
        children: [{ _key: "c2", _type: "span", text: "The Paradigm Shift: From Giant Monoliths to Tiered SLMs" }],
      },
      {
        _key: "b3",
        _type: "block",
        style: "normal",
        children: [{ _key: "c3", _type: "span", text: "Over 78% of typical enterprise queries do not require frontier-tier 500-billion-parameter reasoning. Specialized 7B to 14B parameter models, quantized to 4-bit INT4 or FP8, consistently match larger systems on text classification, semantic extraction, and structured JSON output while running at 15x lower latency." }],
      },
      {
        _key: "b4",
        _type: "callout",
        callout: {
          tone: "tip",
          title: "Production Rule of Thumb",
          text: "Route 80% of routine categorization and transformation requests to localized, quantized SLMs hosted on cost-effective GPUs. Reserve frontier reasoning APIs strictly for complex, multi-hop contextual workflows.",
        },
      },
      {
        _key: "b5",
        _type: "block",
        style: "h2",
        children: [{ _key: "c5", _type: "span", text: "Understanding KV Cache Bottlenecks in Long-Context Applications" }],
      },
      {
        _key: "b6",
        _type: "block",
        style: "normal",
        children: [{ _key: "c6", _type: "span", text: "When running 128k context windows, key-value (KV) cache memory rapidly eclipses the actual parameter weights of the neural network. Without dynamic paging (such as vLLM's PagedAttention) and attention chunking, concurrency is severely throttled." }],
      },
      {
        _key: "b7",
        _type: "codeBlock",
        codeBlock: {
          language: "typescript",
          filename: "llm-router.ts",
          code: `// Multi-tiered smart model router based on query complexity score
export async function routeInference(prompt: string, estimatedTokens: number) {
  const complexity = evaluateComplexity(prompt);
  
  if (complexity < 0.4 && estimatedTokens < 2048) {
    // Fast path: Self-hosted local 8B model via vLLM
    return callLocalInference({ endpoint: process.env.VLLM_URL, prompt });
  }

  // Complex multi-step reasoning: Frontier API with strict timeout
  return callFrontierModel({ prompt, timeoutMs: 4000 });
}`,
        },
      },
      {
        _key: "b8",
        _type: "block",
        style: "h2",
        children: [{ _key: "c8", _type: "span", text: "Latency & Cost Comparison Table" }],
      },
      {
        _key: "b9",
        _type: "table",
        table: {
          headers: ["Architecture Tier", "TTFT (ms)", "Tokens/sec", "Cost per 1M Tokens"],
          rows: [
            ["Frontier Cloud API", "480ms", "45", "$3.50"],
            ["Self-Hosted 14B (FP8)", "65ms", "140", "$0.32"],
            ["Edge Distilled (INT4)", "18ms", "260", "$0.08"],
          ],
        },
      },
      {
        _key: "b10",
        _type: "block",
        style: "h2",
        children: [{ _key: "c10", _type: "span", text: "Frequently Asked Questions" }],
      },
      {
        _key: "b11",
        _type: "faqBlock",
        faq: [
          {
            question: "Is speculative decoding effective for streaming chatbot user experiences?",
            answer: "Yes. By running a tiny draft model alongside the main model, speculative decoding delivers an average 2.1x to 2.8x speedup on token generation without altering final output distributions.",
          },
          {
            question: "How do you protect against prompt injection in automated pipeline agents?",
            answer: "Implement strict schema boundaries using JSON Schema constraints, run dual-evaluator filtering models on user input, and separate tool execution tokens into isolated compute sandboxes.",
          },
        ],
      },
    ],
  },
  {
    _id: "post-2",
    title: "Smart Wealth Building in India: A Masterclass in Mutual Funds, SGBs, and Tax-Loss Harvesting",
    slug: "smart-wealth-building-india-mutual-funds-tax-strategy",
    excerpt: "Demystifying modern personal finance for Indian salaried professionals and entrepreneurs. How to balance active equity, index SIPs, and sovereign gold while navigating revised capital gains rules.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1600&q=85",
      alt: "Financial charts on computer display showing growth and portfolio analytics",
      caption: "Strategic asset allocation forms the bedrock of long-term capital preservation in volatile markets.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[1],
    tags: [MOCK_TAGS[2], MOCK_TAGS[3], MOCK_TAGS[7]],
    author: MOCK_AUTHORS[1],
    publishedAt: "2026-10-05T08:00:00.000Z",
    updatedAt: "2026-10-06T11:20:00.000Z",
    readingTime: 7,
    seoTitle: "Smart Wealth Building in India: Mutual Funds, SGBs & Tax Strategy",
    seoDescription: "Proven blueprint for building lasting wealth in India. Learn optimal asset allocation, index funds vs flexi-caps, and capital gains tax planning.",
    featured: false,
    trending: true,
    views: 11890,
    body: [
      {
        _key: "fb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "fc1", _type: "span", text: "India's macroeconomic growth trajectory offers unprecedented compounding opportunities for disciplined investors. However, chasing trendy momentum stocks and high-churn trading usually yields disappointing after-tax results compared to structured asset allocation." }],
      },
      {
        _key: "fb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "fc2", _type: "span", text: "The Three-Pillar Allocation Framework" }],
      },
      {
        _key: "fb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "fc3", _type: "span", text: "A resilient portfolio balances high-growth equity engines with defensive ballast: 65% diversified domestic equities (via Nifty 50, Midcap 150, and Flexi-cap funds), 20% fixed income (Target Maturity Debt Funds, EPF, and PPF), and 15% alternative stores of value including Sovereign Gold Bonds." }],
      },
      {
        _key: "fb4",
        _type: "callout",
        callout: {
          tone: "info",
          title: "Revised Capital Gains Tax Insight",
          text: "Under current Indian tax provisions, long-term capital gains (LTCG) on listed equities above ₹1.25 Lakh are taxed at 12.5%. Tax-loss harvesting before the financial year closure on March 31st can legally reduce liability by setting off capital losses against taxable gains.",
        },
      },
      {
        _key: "fb5",
        _type: "block",
        style: "h2",
        children: [{ _key: "fc5", _type: "span", text: "Asset Allocation Matrix for Long-Term Horizons" }],
      },
      {
        _key: "fb6",
        _type: "table",
        table: {
          headers: ["Asset Category", "Target Allocation", "Expected Real Return", "Liquidity Profile"],
          rows: [
            ["Nifty 50 & Large Cap", "40%", "7-9% (Net of Inflation)", "T+1 Business Day"],
            ["Mid & Small Cap Index", "25%", "9-11% (Net of Inflation)", "T+1 Business Day"],
            ["Debt & Emergency Buffer", "20%", "2-3% (Net of Inflation)", "Same Day / Immediate"],
            ["Sovereign Gold / Hedging", "15%", "4-6% (Net of Inflation)", "Traded on NSE/BSE"],
          ],
        },
      },
      {
        _key: "fb7",
        _type: "block",
        style: "h2",
        children: [{ _key: "fc7", _type: "span", text: "Common Portfolio Pitfalls" }],
      },
      {
        _key: "fb8",
        _type: "block",
        style: "normal",
        children: [{ _key: "fc8", _type: "span", text: "The most frequent error observed among emerging professionals is fund portfolio sprawl: holding 15+ mutual funds with over 70% portfolio overlap. A disciplined portfolio of 3 to 4 distinct funds accomplishes superior risk management with minimal fee drag." }],
      },
    ],
  },
  {
    _id: "post-3",
    title: "The Science of High-Performance Sleep: Circadian Biology, Adenosine, and Deep-Phase Recovery",
    slug: "science-of-high-performance-sleep-circadian-biology",
    excerpt: "Evidence-backed protocols from neurobiology and clinical sleep research to elevate slow-wave restorative sleep, optimize mental clarity, and maintain sustainable executive energy.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1600&q=85",
      alt: "Tranquil bedroom with morning light entering through curtains, evoking deep sleep and circadian synchronization",
      caption: "Synchronizing photic stimulation with natural circadian biology drastically enhances REM and slow-wave sleep.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[2],
    tags: [MOCK_TAGS[4], MOCK_TAGS[5]],
    author: MOCK_AUTHORS[2],
    publishedAt: "2026-10-04T07:15:00.000Z",
    readingTime: 6,
    seoTitle: "The Science of High-Performance Sleep: Neurobiology & Recovery Protocols",
    seoDescription: "Evidence-based protocols to maximize deep sleep and REM recovery. Learn circadian light timing, temperature control, and supplementation.",
    featured: false,
    trending: false,
    views: 8940,
    body: [
      {
        _key: "sb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "sc1", _type: "span", text: "Sleep is not merely the cessation of conscious activity; it is the most metabolically active neurological repair process your body undergoes. During deep slow-wave sleep (NREM Stage 3), your brain's glymphatic system flushes cellular debris and beta-amyloid plaques accumulated during wakefulness." }],
      },
      {
        _key: "sb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "sc2", _type: "span", text: "Circadian Timing and Photic Stimulation" }],
      },
      {
        _key: "sb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "sc3", _type: "span", text: "Your suprachiasmatic nucleus (SCN) relies on solar light to calibrate cortisol and melatonin rhythms. Viewing unfiltered natural morning light within 45 minutes of waking triggers an accurate circadian countdown for melatonin secretion approximately 14 to 16 hours later." }],
      },
      {
        _key: "sb4",
        _type: "callout",
        callout: {
          tone: "tip",
          title: "The Temperature Trigger",
          text: "Core body temperature must drop by roughly 1°C to initiate and sustain deep sleep. Keep bedroom ambient temperature between 18°C and 20°C (65°F - 68°F) for maximum slow-wave duration.",
        },
      },
      {
        _key: "sb5",
        _type: "block",
        style: "h2",
        children: [{ _key: "sc5", _type: "span", text: "Actionable Evening Protocol" }],
      },
      {
        _key: "sb6",
        _type: "block",
        style: "normal",
        children: [{ _key: "sc6", _type: "span", text: "1. Terminate caffeine intake at least 10 hours prior to targeted sleep onset to permit adenosine clearance. 2. Eliminate high-intensity overhead lighting after sunset. 3. Avoid caloric meals within 3 hours of bed to prevent nighttime heart-rate spikes." }],
      },
    ],
  },
  {
    _id: "post-4",
    title: "Digital Nomad Living in 2026: The Comprehensive Visa, Tax, and Remote Gear Blueprint",
    slug: "digital-nomad-living-2026-visas-taxes-gear-guide",
    excerpt: "Everything you need to know about working remotely across Southeast Asia, Europe, and Latin America. We break down the top nomad visas, tax residency rules, and the battle-tested portable office stack.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=85",
      alt: "Remote worker typing on modern laptop overlooking tropical mountain vista",
      caption: "Balancing productivity and exploration requires rigorous equipment checklists and clear legal planning.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[3],
    tags: [MOCK_TAGS[6]],
    author: MOCK_AUTHORS[0],
    publishedAt: "2026-10-03T09:40:00.000Z",
    readingTime: 9,
    seoTitle: "Digital Nomad Living Guide 2026: Visas, Tax Residency & Remote Gear",
    seoDescription: "The authoritative guide to digital nomad visas, 183-day tax residency traps, ergonomic portable tech stacks, and top hubs for 2026.",
    featured: false,
    trending: false,
    views: 7420,
    body: [
      {
        _key: "nb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "nc1", _type: "span", text: "The global nomad ecosystem has transformed from backpacker improvisations into sophisticated international living frameworks. With more than 60 countries offering dedicated digital nomad visas, mobile professionals can now reside legally with predictable tax and banking infrastructure." }],
      },
      {
        _key: "nb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "nc2", _type: "span", text: "Navigating the 183-Day Tax Residency Trap" }],
      },
      {
        _key: "nb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "nc3", _type: "span", text: "A widespread myth among remote workers is that entering on a tourist visa allows indefinitely tax-free earnings. Crossing the 183-day threshold in any single sovereign jurisdiction frequently subjects your worldwide income to local taxes. Always clarify bilateral Double Taxation Avoidance Agreements (DTAA) beforehand." }],
      },
      {
        _key: "nb4",
        _type: "callout",
        callout: {
          tone: "warning",
          title: "Legal Health Warning",
          text: "Never operate on a standard tourist stamp when generating client billings if the destination offers an explicit remote work visa. Enforcement has tightened dramatically across the EU and ASEAN.",
        },
      },
    ],
  },
  {
    _id: "post-5",
    title: "From Seed to Scale: The Non-Obvious Playbook for Building Resilient Indian Startups",
    slug: "seed-to-scale-resilient-indian-startups-playbook",
    excerpt: "Insights from founders navigating the shift from vanity GMV growth to real operating margins. Why sustainable unit economics and disciplined customer acquisition triumph in the current venture cycle.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1600&q=85",
      alt: "Startup executive team analyzing growth metrics on whiteboard in modern Bangalore office",
      caption: "True product-market fit in India is defined by repeat organic retention rather than aggressive burn-driven CAC subsidies.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[4],
    tags: [MOCK_TAGS[7], MOCK_TAGS[9]],
    author: MOCK_AUTHORS[1],
    publishedAt: "2026-10-02T11:00:00.000Z",
    readingTime: 7,
    seoTitle: "Building Resilient Indian Startups: Unit Economics & Scale Playbook",
    seoDescription: "Actionable frameworks for early-stage and growth founders in India: mastering CAC/LTV, hiring core engineering leaders, and managing venture burn.",
    featured: false,
    trending: true,
    views: 9630,
    body: [
      {
        _key: "bb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "bc1", _type: "span", text: "The exuberance of unconstrained blitzscaling has given way to disciplined venture construction across India's vibrant startup hubs in Bengaluru, Delhi NCR, and Hyderabad. Today's top founders optimize for positive gross margins from day one." }],
      },
      {
        _key: "bb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "bc2", _type: "span", text: "The Fallacy of Blended Customer Acquisition Cost" }],
      },
      {
        _key: "bb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "bc3", _type: "span", text: "Blending organic viral word-of-mouth with paid ad spends obscures paid CAC degradation. Healthy companies isolate paid performance metrics strictly: every customer acquired through performance advertising must demonstrate cash break-even within 90 days." }],
      },
    ],
  },
  {
    _id: "post-6",
    title: "M4 Pro MacBook Pro Deep Dive: Battery Efficiency, Local LLM Inference, and Developer Benchmarks",
    slug: "m4-pro-macbook-pro-deep-dive-developer-benchmarks",
    excerpt: "We benchmark Apple's M4 Pro silicon through intense real-world workloads: compiling massive Next.js 15 codebases, running Llama 3 quantized models locally, and running multi-container Kubernetes pods.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=85",
      alt: "Sleek metallic MacBook Pro laptop on minimalist wooden desk surrounded by developer workspace",
      caption: "Apple's unified memory architecture remains a game changer for local machine learning model evaluation.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[0],
    tags: [MOCK_TAGS[0], MOCK_TAGS[8]],
    author: MOCK_AUTHORS[0],
    publishedAt: "2026-10-01T14:20:00.000Z",
    readingTime: 6,
    seoTitle: "M4 Pro MacBook Pro Review: Developer Benchmarks & Local LLM Tests",
    seoDescription: "Exhaustive hardware review of the M4 Pro MacBook Pro for developers: compilation speeds, memory bandwidth, thermals, and local AI inference numbers.",
    featured: false,
    trending: false,
    views: 6510,
    body: [
      {
        _key: "mb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "mc1", _type: "span", text: "Apple Silicon has steadily matured, but the M4 Pro represents a noticeable qualitative leap in memory bandwidth and neural compute efficiency. For full-stack developers and data engineers, the ability to run 24GB+ weights in unified RAM while retaining 16 hours of untethered battery life changes daily workflows." }],
      },
      {
        _key: "mb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "mc2", _type: "span", text: "Compilation Speeds: Next.js & Rust Crates" }],
      },
      {
        _key: "mb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "mc3", _type: "span", text: "In clean Turbopack builds of a 300-page Next.js project, the M4 Pro clocked in at 4.2 seconds compared to 7.8 seconds on M2 Pro. Zero thermal throttling was observed across 30 consecutive build runs." }],
      },
    ],
  },
  {
    _id: "post-7",
    title: "RBI's Digital Rupee (e₹) Explained: How Retail CBDC and UPI Interoperability Transform Payments",
    slug: "rbi-digital-rupee-cbdc-upi-interoperability-explained",
    excerpt: "Everything you need to know about the Reserve Bank of India's Central Bank Digital Currency. We demystify offline transactions, privacy guarantees, and how QR interoperability merges e₹ with UPI.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1600&q=85",
      alt: "Smartphone processing contactless QR digital payment at point of sale counter",
      caption: "CBDC offers legal tender sovereign backing directly on mobile handsets without bank intermediation.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[1],
    tags: [MOCK_TAGS[2], MOCK_TAGS[7]],
    author: MOCK_AUTHORS[1],
    publishedAt: "2026-09-30T10:15:00.000Z",
    readingTime: 5,
    seoTitle: "RBI Digital Rupee (CBDC) Explained: UPI Interoperability & Tech Architecture",
    seoDescription: "In-depth guide to India's retail Central Bank Digital Currency (e₹-R): offline capabilities, programmable subsidies, and differences from bank deposits.",
    featured: false,
    trending: false,
    views: 5210,
    body: [
      {
        _key: "cb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "cc1", _type: "span", text: "India's Unified Payments Interface (UPI) is already the undisputed crown jewel of global instant retail payments. Why, then, has the Reserve Bank of India developed the Central Bank Digital Currency (e₹)? The answer lies in sovereign liability, programmable money, and offline transaction capabilities." }],
      },
      {
        _key: "cb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "cc2", _type: "span", text: "Sovereign Currency vs Bank Deposits" }],
      },
      {
        _key: "cb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "cc3", _type: "span", text: "When you hold funds in a commercial bank account and initiate a UPI transfer, you are transferring private commercial bank liability backed by deposit insurance up to ₹5 Lakh. When you hold e₹ in your digital wallet, it is a direct claim on the central bank balance sheet, functionally identical to physical paper cash." }],
      },
    ],
  },
  {
    _id: "post-8",
    title: "Zone 2 Cardio Protocols for Longevity: How to Test, Train, and Accurately Track Mitochondrial Density",
    slug: "zone-2-cardio-protocols-longevity-mitochondrial-health",
    excerpt: "Why the easiest cardiovascular pace is your most powerful tool for metabolic flexibility, insulin sensitivity, and cellular longevity. Complete testing guidelines and weekly training templates.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1600&q=85",
      alt: "Athlete jogging at steady conversational pace along scenic coastal path during golden hour",
      caption: "Steady-state aerobic base training maximizes mitochondrial biogenesis and fat oxidation efficiency.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[2],
    tags: [MOCK_TAGS[5]],
    author: MOCK_AUTHORS[2],
    publishedAt: "2026-09-28T07:45:00.000Z",
    readingTime: 6,
    seoTitle: "Zone 2 Cardio Protocols for Longevity: Mitochondrial Health & Testing Guide",
    seoDescription: "The clinical case for low-intensity steady-state cardio. Discover lactate threshold testing, conversational test markers, and optimal weekly volume.",
    featured: false,
    trending: false,
    views: 4890,
    body: [
      {
        _key: "zb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "zc1", _type: "span", text: "In an era obsessed with High-Intensity Interval Training (HIIT), clinical sports science has decisively proven that the true engine of cardiometabolic resilience is low-intensity, steady Zone 2 training. Exercising at an intensity where blood lactate remains below 2.0 mmol/L forces your muscle fibers to utilize fats as their primary fuel substrate." }],
      },
      {
        _key: "zb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "zc2", _type: "span", text: "The Conversational 'Talk Test' Benchmark" }],
      },
      {
        _key: "zb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "zc3", _type: "span", text: "If you do not have access to a finger-prick lactate analyzer or metabolic cart, the conversational test is remarkably accurate: you should be able to speak in full, complete sentences, but with enough effort that the person on the other end of a phone call knows you are actively exercising." }],
      },
    ],
  },
  {
    _id: "post-9",
    title: "The Ultimate Spiti Valley Road Odyssey: Itinerary, Acclimatization Science, and Hidden Monasteries",
    slug: "spiti-valley-road-trip-itinerary-acclimatization-guide",
    excerpt: "Planning an overland journey across Himachal's cold desert. Essential survival advice on acute mountain sickness (AMS), vehicle preparedness, remote connectivity, and cultural etiquette in high-altitude gompas.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=85",
      alt: "Breathtaking high-altitude rugged mountain peaks and turquoise river winding through Spiti Valley",
      caption: "Spiti's ancient geological formations and remote monasteries offer unparalleled tranquility.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[3],
    tags: [MOCK_TAGS[6], MOCK_TAGS[7]],
    author: MOCK_AUTHORS[0],
    publishedAt: "2026-09-26T08:30:00.000Z",
    readingTime: 8,
    seoTitle: "Spiti Valley Road Trip Guide: Acclimatization, Itinerary & Monastery Circuit",
    seoDescription: "Exhaustive travel blueprint for visiting Spiti Valley: Shimla vs Manali routes, Diamox protocols, homestays in Langza and Komic, and packing essentials.",
    featured: false,
    trending: false,
    views: 6120,
    body: [
      {
        _key: "tb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "tc1", _type: "span", text: "Known as 'The Middle Land' nestled between India and Tibet, Spiti Valley is a raw wonderland of stark scree slopes, 1000-year-old Buddhist monasteries, and high-altitude passes. However, with average altitudes exceeding 3,800 meters (12,500 feet), respectful preparation is essential." }],
      },
      {
        _key: "tb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "tc2", _type: "span", text: "The Golden Rule: The Gradual Shimla Ascent" }],
      },
      {
        _key: "tb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "tc3", _type: "span", text: "While entering via Manali through the Atal Tunnel feels tempting for speed, doing so exposes travelers to rapid altitude ascent and high risk of acute mountain sickness (AMS). Opt for the Hindustan-Tibet road via Shimla, Sangla, and Kalpa to permit gradual physiological acclimatization." }],
      },
    ],
  },
  {
    _id: "post-10",
    title: "The Staff Engineer to Director Transition: Influence Without Authority and Strategic Leverage",
    slug: "staff-engineer-to-director-transition-engineering-leadership",
    excerpt: "Transitioning from individual technical mastery to organizational stewardship. How to shift your metrics from lines of code to engineering culture, retention, and multi-year architectural bets.",
    mainImage: {
      url: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=85",
      alt: "Senior engineering leader mentoring team members in open modern engineering collaborative space",
      caption: "True executive engineering leadership is about creating high-trust environments where great decisions emerge naturally.",
      width: 1600,
      height: 900,
    },
    category: MOCK_CATEGORIES[4],
    tags: [MOCK_TAGS[9]],
    author: MOCK_AUTHORS[0],
    publishedAt: "2026-09-24T12:00:00.000Z",
    readingTime: 7,
    seoTitle: "Staff Engineer to Director: Engineering Leadership Transition Playbook",
    seoDescription: "Practical guide for senior technologists navigating the management leap: stakeholder diplomacy, team empowerment, and measuring technical leverage.",
    featured: false,
    trending: false,
    views: 7850,
    body: [
      {
        _key: "eb1",
        _type: "block",
        style: "normal",
        children: [{ _key: "ec1", _type: "span", text: "The psychological leap from Senior Staff Engineer to Engineering Director is one of the steepest in tech. As an individual contributor, dopamine comes from shipping PRs, solving knotty distributed race conditions, and technical consensus. As a Director, your code is the organization itself." }],
      },
      {
        _key: "eb2",
        _type: "block",
        style: "h2",
        children: [{ _key: "ec2", _type: "span", text: "Managing Your Time: From Maker to Multiplier" }],
      },
      {
        _key: "eb3",
        _type: "block",
        style: "normal",
        children: [{ _key: "ec3", _type: "span", text: "If you continue to code in the critical path, you become the single point of failure and bottleneck for your teams. Your primary output is clarity of context, hiring and mentoring outstanding engineering managers, and maintaining engineering excellence across multiple quarters." }],
      },
    ],
  },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    _id: "news-ai-datacenter-expansion",
    title: "Global Cloud Giants Commit $18B to Next-Gen Indian AI & Clean Energy Data Hubs",
    slug: "global-cloud-giants-commit-18b-india-ai-data-hubs",
    category: "Technology",
    isBreaking: true,
    publishedAt: "2026-10-08T09:30:00.000Z",
    source: "BlueCrest Tech Desk",
    sourceUrl: "https://bluecreast.in",
    readingTime: 3,
    summary:
      "A consortium of hyperscalers and renewable energy pioneers have announced massive hyper-scale data centers powered by dedicated solar and pumped hydro storage across Maharashtra and Tamil Nadu.",
    highlights: [
      "Over $18 Billion pledged across high-density GPU computing infrastructure by Q4 2027.",
      "100% renewable power purchase agreements locked with regional green grids.",
      "Expected to generate 45,000 direct and indirect engineering and facility jobs in India.",
    ],
    author: MOCK_AUTHORS[0],
    mainImage: {
      url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
      alt: "Futuristic server room with blue neon lights and optical fiber interconnects",
      caption: "High-density AI server clusters running sustainable green microgrid architectures.",
    },
    content:
      "In an unprecedented expansion of sovereign compute, major infrastructure conglomerates have confirmed groundbreaking ceremonies for two ultra-dense AI training campuses. The facilities will host next-generation custom silicon arrays tailored for multi-modal reasoning and localized open-source foundational models.",
    tags: ["Artificial Intelligence", "Cloud Infrastructure", "India Growth"],
  },
  {
    _id: "news-rbi-fintech-crossborder",
    title: "RBI & Global Central Banks Expand Instant Cross-Border UPI Settlement to 14 Nations",
    slug: "rbi-expands-instant-cross-border-upi-settlement-14-nations",
    category: "Markets & Finance",
    isBreaking: false,
    publishedAt: "2026-10-08T07:15:00.000Z",
    source: "BlueCrest Markets Desk",
    readingTime: 4,
    summary:
      "The Reserve Bank of India has expanded real-time sovereign payments bilateral linkages, slashing cross-border remittance fees by up to 80% for expat families and small exporters.",
    highlights: [
      "Bilateral bilateral corridors live across Europe, Middle East, and Southeast Asia.",
      "Average settlement latency reduced from 48 hours via SWIFT to under 8 seconds.",
      "Estimated $4.2B in annual transaction fees returned to micro-enterprises and families.",
    ],
    author: MOCK_AUTHORS[1],
    mainImage: {
      url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
      alt: "Mobile device showing successful digital payments transaction confirmation",
      caption: "Real-time sovereign digital rails are transforming global remittance corridors.",
    },
    content:
      "Following successful bilateral pilot programs, the Reserve Bank of India announced the formal operationalization of instant cross-border settlement protocols. The initiative bypasses conventional correspondent banking intermediaries, utilizing direct central-bank foreign currency swap lines.",
    tags: ["Fintech", "UPI", "Banking", "Economy"],
  },
  {
    _id: "news-breakthrough-solidstate-battery",
    title: "Scientists Confirm 1,000km Range Breakthrough with High-Density Solid-State EV Cells",
    slug: "scientists-confirm-1000km-range-solid-state-ev-cells",
    category: "Science & Health",
    isBreaking: true,
    publishedAt: "2026-10-07T16:45:00.000Z",
    source: "BlueCrest Science Desk",
    readingTime: 3,
    summary:
      "Peer-reviewed university lab trials demonstrate lithium-sulfur ceramic electrolytes enduring 2,500 rapid charge cycles with negligible degradation and non-flammable safety profile.",
    highlights: [
      "Energy density reaches 520 Wh/kg, double current commercial lithium-ion cells.",
      "Charges from 10% to 80% state of charge in 9 minutes without thermal runaway.",
      "Pilot automotive integration trials slated with top two EV manufacturers for 2027.",
    ],
    author: MOCK_AUTHORS[2],
    mainImage: {
      url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1200&q=80",
      alt: "Electric vehicle rapid charging station with modern sleek illuminated interface",
      caption: "Next-generation solid-state battery cells eliminate range anxiety and fire risk.",
    },
    content:
      "Researchers at the National Institute of Advanced Materials have published verified bench test results for a ceramic-based solid electrolyte that prevents dendrite formation under ultra-high current densities. The development represents the largest single leap in portable electrochemical storage in two decades.",
    tags: ["Clean Energy", "Electric Vehicles", "Materials Science"],
  },
  {
    _id: "news-sensex-nifty-all-time-high",
    title: "Indian Equities Surge to Fresh Records as Domestic Inflows Cross ₹30,000 Crore",
    slug: "indian-equities-surge-fresh-records-domestic-inflows",
    category: "Markets & Finance",
    isBreaking: false,
    publishedAt: "2026-10-07T11:20:00.000Z",
    source: "BlueCrest Markets Desk",
    readingTime: 3,
    summary:
      "Strong corporate earnings, capital expenditure cycles, and uninterrupted monthly retail SIP participation propel benchmark indices to historic summits.",
    highlights: [
      "Nifty 50 breaches psychological barrier led by capital goods and private lenders.",
      "Monthly mutual fund SIP collections hit an all-time monthly high of ₹31,200 Cr.",
      "FIIs turn net buyers after three consecutive quarters of defensive asset reallocation.",
    ],
    author: MOCK_AUTHORS[1],
    mainImage: {
      url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80",
      alt: "Stock market financial charts with ascending green candles and trading terminal display",
      caption: "Resilient domestic institutional liquidity drives equity valuations to historic levels.",
    },
    content:
      "Domestic equity markets rallied strongly in trade today, anchored by robust balance sheets across the industrial capital goods sector and record systematic investment inflows. Analysts note that structural participation from young retail investors continues to provide a dependable cushion against global macro volatility.",
    tags: ["Sensex", "Investing", "Mutual Funds", "Markets"],
  },
  {
    _id: "news-open-source-ai-models",
    title: "New Open Weights Reasoning Model Matches Closed Frontiers on Coding & Math",
    slug: "new-open-weights-reasoning-model-matches-closed-frontiers",
    category: "Technology",
    isBreaking: false,
    publishedAt: "2026-10-06T18:00:00.000Z",
    source: "BlueCrest Tech Desk",
    readingTime: 4,
    summary:
      "Independent researchers have released an open 70B parameter reasoning model that matches commercial proprietary models across HumanEval and SWE-bench benchmarks.",
    highlights: [
      "Achieves 89.4% on GSM8K and solves 61.2% of verified SWE-bench software engineering tasks.",
      "Permissive Apache 2.0 weights distributed for enterprise local deployment.",
      "Runs fully quantized on single 48GB GPU workstations with sub-second response times.",
    ],
    author: MOCK_AUTHORS[0],
    mainImage: {
      url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
      alt: "Green digital code streaming on dark monitor terminal screen",
      caption: "Open-source foundational architectures are closing the performance gap rapidly.",
    },
    content:
      "The democratization of high-level chain-of-thought AI achieved another milestone today with the public release of DeepReason-70B. Evaluated under rigorous third-party auditing environments, the open weights checkpoint demonstrates verifiable deductive reasoning capabilities previously exclusive to subscription-based APIs.",
    tags: ["Open Source", "Artificial Intelligence", "Software Engineering"],
  },
  {
    _id: "news-national-semiconductor-mission",
    title: "First Commercial Silicon Wafers Fabricated Under India's Semiconductor Mission",
    slug: "first-commercial-silicon-wafers-fabricated-india-semiconductor-mission",
    category: "Startups & Business",
    isBreaking: false,
    publishedAt: "2026-10-05T14:10:00.000Z",
    source: "BlueCrest Wire",
    readingTime: 3,
    summary:
      "Pilot production runs of 28nm legacy automotive and industrial microcontrollers yield successful test passes at the Dholera semiconductor fab cluster.",
    highlights: [
      "Pilot test wafers attain 94.2% operational die yield across automated quality inspections.",
      "Commercial volume ramp-up scheduled to commence deliveries by Q2 2027.",
      "Reduces supply chain dependency for domestic automotive and IoT hardware makers.",
    ],
    author: MOCK_AUTHORS[0],
    mainImage: {
      url: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      alt: "Microchip processor silicon die closeup with intricate golden circuits",
      caption: "India's semiconductor manufacturing ecosystem delivers its first verified test silicon.",
    },
    content:
      "In a milestone moment for domestic high-technology manufacturing, engineers at the Dholera cleanroom facility reported successful qualification of the first batch of 300mm silicon wafers. The chips, optimized for electric vehicle power management and industrial automation, mark the operational realization of the India Semiconductor Mission.",
    tags: ["Semiconductors", "Manufacturing", "Hardware", "India"],
  },
];
